// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaMzaxda5gQWW-w0uS9FWvS-MgR3CNoqQ',
    appId: '1:497468888138:web:854443d0ff0f280f0a02b3',
    messagingSenderId: '497468888138',
    projectId: 'meeting-app-b240e',
    authDomain: 'meeting-app-b240e.firebaseapp.com',
    storageBucket: 'meeting-app-b240e.firebasestorage.app',
    measurementId: 'G-Y5T4G97EVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHr1S_05BH2qYixgXzzxNlFiZXMUTbl-w',
    appId: '1:497468888138:android:a170017e3943d0bd0a02b3',
    messagingSenderId: '497468888138',
    projectId: 'meeting-app-b240e',
    storageBucket: 'meeting-app-b240e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWM1NgI-JBHnQlt0Rh3UW47kkLJT73nFI',
    appId: '1:497468888138:ios:9776bb2736adef850a02b3',
    messagingSenderId: '497468888138',
    projectId: 'meeting-app-b240e',
    storageBucket: 'meeting-app-b240e.firebasestorage.app',
    iosBundleId: 'com.example.flutterMeetingApp',
  );
}
